### PR TITLE
Enhance triggering steps phrases with "each"

### PR DESCRIPTION
**Pull request by suwapp**
Some cards uses "each" instead of "the" when referring to a certain phase. Roughly 33 cards are affected. Updating every phase for consistency.

https://hallofbeorn.com/LotR?Query=beginning+of+each
https://hallofbeorn.com/LotR?Query=end+of+each
https://hallofbeorn.com/LotR?Query=during+each

### CODE REVIEW

**Comment by suwapp** [comment]
Only text edits, have not compiled/run any tests or checks.

**Comment by seastan** [comment]
Thank you! Do you mind redirecting your PR to the development branch?

**Comment by suwapp** [comment]
Bah, I need to rebase my branch. I'm from UI now, will need to take a look how to do that.

**Comment by suwapp** [comment]
I'm creating a new pr.

**Pull request closed without merging**
